### ISSUE TITLE
Missing file?

### ISSUE THREAD

**Issue by ibanez0r** [bonecode/Components#1]
[dcc32 Fatal Error] BCControlsRXE8.dpk(67): F2613 Unit '..\Source\BCControls.CheckBox.pas' not found.

**Comment by bonecode** [comment]
Fixed.

**Comment by ibanez0r** [comment]
awesome thanks, does this project also have design time code in its runtime libs as well, would be good to straighten that up, sorry if im way off its been a while im going from memory

**Comment by bonecode** [comment]
This "project" includes components for my software. Most of these are wrappers to enable single point bug fixing and customizing.

It is is divided into runtime and designtime packages. Naming was in old style, so I changed it.

**Comment by ibanez0r** [comment]
well, nice work on that m8, cheers
