### ISSUE TITLE
GetImageIndex  parameters list is changed in the current release of Virtual TreeView

### ISSUE THREAD

**Issue by delphioracle** [bonecode/Components#2]
procedure TBCFileTreeView.PaintImage(var PaintInfo: TVTPaintInfo; ImageInfoIndex: TVTImageInfoIndex; DoOverlay: Boolean);
var
  Data: PBCFileTreeNodeRec;
begin
  with PaintInfo do
  begin
    Data := GetNodeData(Node);

    if Data.SaturateImage then
    begin
      if DoOverlay then
        GetImageIndex(PaintInfo, ikOverlay, {iiOverlay, Images}ImageInfoIndex)     //oan!!!-NOT TESTED

**Comment by bonecode** [comment]
I am using the latest release 6.2.3 and that change is not there yet. I will not use the current trunk because it is not stable. Sure, that will be fixed as soon as there are stable release.

**Comment by bonecode** [comment]
Now updated for VirtualTree V6.4.
