### ISSUE TITLE
BCControl.ComboBox.pas(81): E2003 Undeclared identifier: 'ColorRectWidth'

### ISSUE THREAD

**Issue by ThomasJaeger** [bonecode/Components#5]
Hi,

First of all, thank you so much for spending the time creating the XE4 packages. I know how hard it it is to find some time to work on these things. I do appreciate all your effort and time in these projects.

I'm still trying to get the TBCEditor working and to be able to learn from the demo source. However, I'm not able to do that because of the dependencies to the other packages.

I'm trying to compile the  BCControls.Delphi.XE4.Runtime package and I'm getting the following error:
 [dcc32 Error] BCControl.ComboBox.pas(81): E2003 Undeclared identifier: 'ColorRectWidth'

Thanks again for your time,
Thomas Jaeger

PS: I'm trying to switch my assembly editor to your editor once I get it all compiled and working. My open source project is located at https://github.com/ThomasJaeger/VisualMASM and my original project site is at http://www.visualmasm.com. It's an IDE for Windows Assembly programmers based on MASM.

**Comment by bonecode** [comment]
BCControl.ComboBox is a wrapper for TsCombobox (AlphaSkins). I have the latest version of AlphaSkins and I don't get any errors. For the demo you don't need that control. So, you can delete it from the package.

BCComponents, BCControls and Common source are not needed for TBCEditor. Demo is just a show case and requires those. Just drop the TBCEditor control on form (or create it dynamically), load highlighter and color from file or stream. That's it, the control should explain itself pretty well.
