### ISSUE TITLE
acntDelphiXE8_R.dpk(29): E2225 Never-build package 'rtl' must be recompiled

### ISSUE THREAD

**Issue by ThomasJaeger** [bonecode/Components#6]
I'm trying to compile the BCComponents.Delphi.XE4.Designtime buyt get the following error:

[dcc32 Fatal Error] acntDelphiXE8_R.dpk(29): E2225 Never-build package 'rtl' must be recompiled

It has a dependency to a Delphi XE8 version in a Delphi XE4 package?

**Comment by bonecode** [comment]
Fixed.
