### ISSUE TITLE
ObjectInspector

### ISSUE THREAD

**Issue by ismailozenc** [bonecode/Components#8]
I am trying to add a panel and an objectinspector to editor demo. As soon as i run the application a red box appears in the middle of the editor. it is always a same size red box. I am guessing it is a hint box but i cant find the source of it. any ideas?

**Comment by bonecode** [comment]
I think that is the token hint property which is still under development. But that red box is not showing anymore. Download the latest source from TBCEditor trunk.

**Comment by ismailozenc** [comment]
thank you. by the way great components. thumbs up
